/* tslint:disable:max-line-length */

export const descriptions = {
    git: {
        subcommands: {
            add: "Add file contents to the index.",
            am: "Apply a series of patches from a mailbox.",
            archive: "Create an archive of files from a named tree.",
            bisect: "Find by binary search the change that introduced a bug.",
            branch: "List, create, or delete branches.",
            bundle: "Move objects and refs by archive.",
            checkout: "Switch branches or restore working tree files.",
            cherryPick: "Apply the changes introduced by some existing commits.",
            citool: "Graphical alternative to git-commit.",
            clean: "Remove untracked files from the working tree.",
            clone: "Clone a repository into a new directory.",
            commit: "Record changes to the repository.",
            config: "Get and set repository or global options",
            describe: "Describe a commit using the most recent tag reachable from it.",
            diff: "Show changes between commits, commit and working tree, etc.",
            fetch: "Download objects and refs from another repository.",
            formatPatch: "Prepare patches for e-mail submission.",
            gc: "Cleanup unnecessary files and optimize the local repository.",
            grep: "Print lines matching a pattern.",
            gui: "A portable graphical interface to Git.",
            init: "Create an empty Git repository or reinitialize an existing one.",
            log: "Show commit logs.",
            merge: "Join two or more development histories together.",
            mv: "Move or rename a file, a directory, or a symlink.",
            notes: "Add or inspect object notes.",
            pull: "Fetch from and integrate with another repository or a local branch.",
            push: "Update remote refs along with associated objects.",
            rebase: "Forward-port local commits to the updated upstream head.",
            reset: "Reset current HEAD to the specified state.",
            revert: "Revert some existing commits.",
            rm: "Remove files from the working tree and from the index.",
            shortlog: "Summarize git log output.",
            show: "Show various types of objects.",
            stash: "Stash the changes in a dirty working directory away.",
            status: "Show the working tree status.",
            submodule: "Initialize, update or inspect submodules.",
            tag: "Create, list, delete or verify a tag object signed with GPG.",
            worktree: "Manage multiple worktrees.",
        },
        add: {
            patch: 'Interactively choose hunks of patch between the index and the work tree and add them to the index. This gives the user a chance to review the difference before adding modified contents to the index. This effectively runs add --interactive, but bypasses the initial command menu and directly jumps to the patch subcommand. See "Interactive mode" for details.',
            interactive: 'Add modified contents in the working tree interactively to the index. Optional path arguments may be supplied to limit operation to a subset of the working tree. See "Interactive mode" for details.',
            dryRun: "Don't actually add the file(s), just show if they exist and/or will be ignored.",
            force: "Allow adding otherwise ignored files.",
            edit: "Open the diff vs. the index in an editor and let the user edit it. After the editor was closed, adjust the hunk headers and apply the patch to the index. The intent of this option is to pick and choose lines of the patch to apply, or even to modify the contents of lines to be staged. This can be quicker and more flexible than using the interactive hunk selector. However, it is easy to confuse oneself and create a patch that does not apply to the index. See EDITING PATCHES below.",
            update: "Update the index just where it already has an entry matching <pathspec>. This removes as well as modifies index entries to match the working tree, but adds no new files. If no <pathspec> is given when -u option is used, all tracked files in the entire working tree are updated (old versions of Git used to limit the update to the current directory and its subdirectories).",
            noIgnoreRemoval: "Update the index not only where the working tree has a file matching <pathspec> but also where the index already has an entry. This adds, modifies, and removes index entries to match the working tree. If no <pathspec> is given when -A option is used, all files in the entire working tree are updated (old versions of Git used to limit the update to the current directory and its subdirectories).",
            ignoreRemoval: 'Update the index by adding new files that are unknown to the index and files modified in the working tree, but ignore files that have been removed from the working tree. This option is a no-op when no <pathspec> is used. This option is primarily to help users who are used to older versions of Git, whose "git add <pathspec>..." was a synonym for "git add --no-all <pathspec>...", i.e. ignored removed files.',
            intentToAdd: "Record only the fact that the path will be added later. An entry for the path is placed in the index with no content. This is useful for, among other things, showing the unstaged content of such files with git diff and committing them with git commit -a.",
            refresh: "Don't add the file(s), but only refresh their stat() information in the index.",
            ignoreErrors: "If some files could not be added because of errors indexing them, do not abort the operation, but continue adding the others. The command shall still exit with non-zero status. The configuration variable add.ignoreErrors can be set to true to make this the default behaviour.",
            ignoreMissing: "This option can only be used together with --dry-run. By using this option the user can check if any of the given files would be ignored, no matter if they are already present in the work tree or not.",
            chmod: "Override the executable bit of the added files. The executable bit is only changed in the index, the files on disk are left unchanged.",
            separator: "This option can be used to separate command-line options from the list of files, (useful when filenames might be mistaken for command-line options).",
            verbose: "Be verbose.",
        },
        checkout: {
            branch: "Create a new branch and start it at <start_point>; see git-branch(1) for details.",
        },
        commit: {
            message: "Use the given <msg> as the commit message. If multiple -m options are given, their values are concatenated as separate paragraphs.",
            all: "Tell the command to automatically stage files that have been modified and deleted, but new files you have not told Git about are not affected.",
            patch: "Use the interactive patch selection interface to chose which changes to commit. See git-add(1) for details.",
            NULL: "When showing short or porcelain status output, terminate entries in the status output with NULL, instead of LF. If no format is given, implies the --porcelain output format.",
            template: "When editing the commit message, start the editor with the contents in the given file. The commit.template configuration variable is often used to give this option implicitly to the command. This mechanism can be used by projects that want to guide participants with some hints on what to write in the message in what order. If the user exits the editor without editing the message, the commit is aborted. This has no effect when a message is given by other means, e.g. with the -m or -F options.",
            signoff: "Add Signed-off-by line by the committer at the end of the commit log message. The meaning of a signoff depends on the project, but it typically certifies that committer has the rights to submit this work under the same license and agrees to a Developer Certificate of Origin (see http://developercertificate.org/ for more information).",
            noVerify: "This option bypasses the pre-commit and commit-msg hooks. See also githooks(5).",
            edit: "The message taken from file with -F, command line with -m, and from commit object with -C are usually used as the commit log message unmodified. This option lets you further edit the message taken from these sources.",
            include: "Before making a commit out of staged contents so far, stage the contents of paths given on the command line as well. This is usually not what you want unless you are concluding a conflicted merge.",
            only: "Make a commit by taking the updated working tree contents of the paths specified on the command line, disregarding any contents that have been staged for other paths. This is the default mode of operation of git commit if any paths are given on the command line, in which case this option can be omitted. If this option is specified together with --amend, then no paths need to be specified, which can be used to amend the last commit without committing changes that have already been staged.",
            verbose: "Show unified diff between the HEAD commit and what would be committed at the bottom of the commit message template to help the user describe the commit by reminding what changes the commit has. Note that this diff output doesn't have its lines prefixed with #. This diff will not be a part of the commit message. See the commit.verbose configuration variable in git-config(1). If specified twice, show in addition the unified diff between what would be committed and the worktree files, i.e. the unstaged changes to tracked files.",
            quiet: "Suppress commit summary message.",
            resetAuthor: "When used with -C/-c/--amend options, or when committing after a a conflicting cherry-pick, declare that the authorship of the resulting commit now belongs to the committer. This also renews the author timestamp.",
            short: "When doing a dry-run, give the output in the short-format. See git-status(1) for details. Implies --dry-run.",
            branch: "Show the branch and tracking info even in short-format.",
            porcelain: "When doing a dry-run, give the output in a porcelain-ready format. See git-status(1) for details. Implies --dry-run.",
            long: "When doing a dry-run, give the output in a the long-format. Implies --dry-run.",
            allowEmpty: "Usually recording a commit that has the exact same tree as its sole parent commit is a mistake, and the command prevents you from making such a commit. This option bypasses the safety, and is primarily for use by foreign SCM interface scripts.",
            allowEmptyMessage: "Like --allow-empty this command is primarily for use by foreign SCM interface scripts. It allows you to create a commit with an empty commit message without using plumbing commands like git-commit-tree(1).",
            noEdit: "Use the selected commit message without launching an editor. For example, git commit --amend --no-edit amends a commit without changing its commit message.",
            noPostRewrite: "Bypass the post-rewrite hook.",
            dryRun: "Do not create a commit, but show a list of paths that are to be committed, paths with local changes that will be left uncommitted and paths that are untracked.",
            status: "Include the output of git-status(1) in the commit message template when using an editor to prepare the commit message. Defaults to on, but can be used to override configuration variable commit.status.",
            noStatus: "Do not include the output of git-status(1) in the commit message template when using an editor to prepare the default commit message.",
            noGpgSign: "Countermand commit.gpgSign configuration variable that is set to force each and every commit to be signed.",
        },
        status: {
            short: "Give the output in the short-format.",
            branch: "Show the branch and tracking info even in short-format.",
            porcelain: "Give the output in an easy-to-parse format for scripts. This is similar to the short output, but will remain stable across Git versions and regardless of user configuration. See below for details. The version parameter is used to specify the format version. This is optional and defaults to the original version v1 format.",
            long: "Give the output in the long-format. This is the default.",
            verbose: "In addition to the names of files that have been changed, also show the textual changes that are staged to be committed (i.e., like the output of git diff --cached). If -v is specified twice, then also show the changes in the working tree that have not yet been staged (i.e., like the output of git diff).",
            untrackedFiles: "Show untracked files. The mode parameter is used to specify the handling of untracked files. It is optional: it defaults to all, and if specified, it must be stuck to the option (e.g.  -uno, but not -u no). The possible options are: o   no - Show no untracked files. o   normal - Shows untracked files and directories. o   all - Also shows individual files in untracked directories. When -u option is not used, untracked files and directories are shown (i.e. the same as specifying normal), to help you avoid forgetting to add newly created files. Because it takes extra work to find untracked files in the filesystem, this mode may take some time in a large working tree. Consider enabling untracked cache and split index if supported (see git update-index --untracked-cache and git update-index --split-index), Otherwise you can use no to have git status return more quickly without showing untracked files. The default can be changed using the status.showUntrackedFiles configuration variable documented in git-config(1).",
            ignoreSubmodules: 'Ignore changes to submodules when looking for changes. <when> can be either "none", "untracked", "dirty" or "all", which is the default. Using "none" will consider the submodule modified when it either contains untracked or modified files or its HEAD differs from the commit recorded in the superproject and can be used to override any settings of the ignore option in git- config(1) or gitmodules(5). When "untracked" is used submodules are not considered dirty when they only contain untracked content (but they are still scanned for modified content). Using "dirty" ignores all changes to the work tree of submodules, only changes to the commits stored in the superproject are shown (this was the behavior before 1.7.0). Using "all" hides all changes to submodules (and suppresses the output of submodule summaries when the config option status.submoduleSummary is set).',
            ignored: "Show ignored files as well.",
            terminateWithNull: "Terminate entries with NUL, instead of LF. This implies the --porcelain=v1 output format if no other format is given.",
            column:
                "Display untracked files in columns. See configuration variable column.status for option syntax.--column and --no-column without options are equivalent to always and never respectively.",
        },
        push: {
            all: "Push all branches (i.e. refs under refs/heads/); cannot be used with other <refspec>.",
            prune: "Remove remote branches that don't have a local counterpart.",
        }
    },
};
