#!/usr/bin/env node
var cp = require('child_process');
var path = require('path');

/* TODO: Get value from argument */
var verbose = false;

process.chdir(path.dirname(__dirname));

var npmInstallation = function(callback) {
	var options = {};

	options.maxBuffer = 1024 * 1024;

	console.log('Installing node modules...');
	var child = cp.exec('npm install', options, function(error, stdout, stderr) {
		if (error)
			process.exit(error.code || 1);
		else
			callback();
	});
	child.stderr.pipe(process.stderr);
	if (verbose) child.stdout.pipe(process.stdout);
};

var bowerInstallation = function(callback) {
	var bowerPath = path.join('node_modules', '.bin', 'bower') + (process.platform === 'win32' ? '.cmd' : '');
	var bowerArgs = ['install'];
	var bowerOptions = {};

	console.log('Installing bower components...');
	var child = cp.spawn(bowerPath, bowerArgs, bowerOptions);
	child.stderr.pipe(process.stderr);
	if (verbose) child.stdout.pipe(process.stdout);
	child.on('error', function(error) {
		console.error('Command \'' + command + '\' failed: ' + error.message);
	});
	child.on('exit', function(code) {
		if (code != 0)
			process.exit(code);
		else
			callback();
	});
};

npmInstallation(function() {
	bowerInstallation(function() { console.log('All dependencies installed correctly!'); });
});